# 6 Implementing Sets, Stacks and Queues

In [1]:
# Project setup
using Pkg
pkg"activate ."

Activating environment at `~/Dropbox/Projects/Julia Data Structures/support_files/Hands-On-Data-Structures-and-Algorithms-with-Julia/Chapter 6/Project.toml`


## Analyzing Julia's Set implementation

In [2]:
Set([1,2,3,4,5,6])

Set([4, 2, 3, 5, 6, 1])

In [3]:
Set('A':'E')

Set(['C', 'D', 'A', 'E', 'B'])

In [4]:
Set()

Set(Any[])

In [5]:
Set(UInt[])

Set(UInt64[])

In [6]:
Set(Float16[1,2,3])

Set(Float16[2.0, 3.0, 1.0])

## Working with Sets

In [7]:
using Random

In [8]:
Random.seed!(0)

MersenneTwister(UInt32[0x00000000], Random.DSFMT.DSFMT_state(Int32[748398797, 1073523691, -1738140313, 1073664641, -1492392947, 1073490074, -1625281839, 1073254801, 1875112882, 1073717145  …  943540191, 1073626624, 1091647724, 1073372234, -1273625233, -823628301, 835224507, 991807863, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x0000000000

In [9]:
myset = rand('A':'Z', 10) |> Set

Set(['K', 'A', 'Y', 'Z', 'V', 'X', 'S', 'Q', 'T'])

In [10]:
in('Z', myset)

true

In [11]:
in('B', myset)

false

In [12]:
push!(myset, 'B')

Set(['B', 'K', 'A', 'Y', 'Z', 'V', 'X', 'S', 'Q', 'T'])

In [13]:
in('B', myset)

true

In [14]:
push!(myset, 'Q')

Set(['B', 'K', 'A', 'Y', 'Z', 'V', 'X', 'S', 'Q', 'T'])

In [15]:
pop!(myset, 'B')

'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)

In [16]:
pop!(myset, 'B')

KeyError: KeyError: key 'B' not found

In [17]:
pop!(myset, 'B', 'b')

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [18]:
pop!(myset, 'A', 'b')

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [19]:
myset

Set(['K', 'Y', 'Z', 'V', 'X', 'S', 'Q', 'T'])

In [20]:
delete!(myset, 'K')

Set(['Y', 'Z', 'V', 'X', 'S', 'Q', 'T'])

In [21]:
length(myset)

7

In [22]:
isempty(myset)

false

In [23]:
empty!(myset)

Set(Char[])

In [24]:
myset

Set(Char[])

## Common Set operations

In [25]:
Random.seed!(0)

MersenneTwister(UInt32[0x00000000], Random.DSFMT.DSFMT_state(Int32[748398797, 1073523691, -1738140313, 1073664641, -1492392947, 1073490074, -1625281839, 1073254801, 1875112882, 1073717145  …  943540191, 1073626624, 1091647724, 1073372234, -1273625233, -823628301, 835224507, 991807863, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x0000000000

In [26]:
setA = Set(rand('A':'Z', 5))

Set(['A', 'Z', 'V', 'S', 'Q'])

In [27]:
setB = Set(rand('a':'z', 5))

Set(['x', 'a', 'y', 'k', 't'])

In [28]:
union(setA, setB)

Set(['A', 'x', 'a', 'y', 'k', 'Z', 'V', 't', 'S', 'Q'])

In [29]:
union(setA, setB, Set(['K', 'Q']))

Set(['Z', 'A', 'y', 'k', 't', 'Q', 'K', 'a', 'S', 'x', 'V'])

In [30]:
intersect(setA, Set(['K', 'Q']))

Set(['Q'])

In [32]:
intersect(setA, setB, Set(['K', 'Q']))

Set(Char[])

In [33]:
union(setA, Set([1,2]))

Set(Any['A', 2, 'Z', 'V', 'S', 'Q', 1])

In [34]:
eltype(ans)

Any

In [35]:
union(setA, [1,2])

Set(Any['A', 2, 'Z', 'V', 'S', 'Q', 1])

In [36]:
union!(setA, setB)

Set(['A', 'x', 'a', 'y', 'k', 'Z', 'V', 't', 'S', 'Q'])

In [37]:
setA

Set(['A', 'x', 'a', 'y', 'k', 'Z', 'V', 't', 'S', 'Q'])

In [38]:
intersect!(setA, setB)

Set(['x', 'a', 'y', 'k', 't'])

In [39]:
setdiff(Set([1, 2, 7, 8, 9]), Set([3, 7]), [8,9])

Set([2, 1])

In [40]:
setX = Set([1, 2, 7, 8, 9])

Set([7, 9, 2, 8, 1])

In [41]:
setdiff!(setX, Set([3, 7]), [8,9])

Set([2, 1])

In [42]:
setX

Set([2, 1])

In [51]:
vowels = Set(['a', 'e', 'i', 'o', 'u'])

Set(['a', 'i', 'e', 'u', 'o'])

In [44]:
letters = Set(['a':'z'...])

Set(['n', 'f', 'w', 'o', 'h', 'i', 't', 'r', 'q', 'a'  …  'b', 'd', 'e', 'j', 's', 'y', 'k', 'm', 'z', 'g', 'l'])

In [45]:
issubset(vowels, letters)

true

In [46]:
⊆(vowels, letters)

true

In [47]:
⊇(letters, vowels)

true

In [48]:
?⊆

"⊆" can be typed by \subseteq<tab>

search: ⊆



```
issubset(a, b)
⊆(a,b)  -> Bool
⊇(b, a) -> Bool
```

Determine whether every element of `a` is also in `b`, using [`in`](@ref).

# Examples

```jldoctest
julia> issubset([1, 2], [1, 2, 3])
true

julia> [1, 2, 3] ⊆ [1, 2]
false

julia> [1, 2, 3] ⊇ [1, 2]
true
```


In [54]:
issetequal(vowels, Set(['a', 'e', 'i', 'o', 'u']))

true

### The BitSet type

In [55]:
s = BitSet(1:10)

BitSet([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [56]:
bitstring(s.bits[1])

"0000000000000000000000000000000000000000000000000000011111111110"

In [57]:
setdiff!(s, [(3:7)...])

BitSet([1, 2, 8, 9, 10])

In [58]:
bitstring(s.bits[1])

"0000000000000000000000000000000000000000000000000000011100000110"

### Ordered sets and sorted sets

In [2]:
using DataStructures

In [12]:
r = Set(1:10)

Set([7, 4, 9, 10, 2, 3, 5, 8, 6, 1])

In [11]:
s = OrderedSet(1:10)

OrderedSet{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [13]:
t = SortedSet(1:10)

SortedSet([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
Base.Order.ForwardOrdering())

In [14]:
push!(t, 0)

SortedSet([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
Base.Order.ForwardOrdering())

In [15]:
push!(s, 0)

OrderedSet{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0])

In [16]:
elems = map(x -> ceil(Int, x*10), rand(10)) |> unique!

6-element Array{Int64,1}:
  5
  4
  3
  2
 10
  6

In [19]:
t = SortedSet(Base.Order.Reverse, elems)

SortedSet([10, 6, 5, 4, 3, 2],
Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering()))

In [20]:
push!(t, 4, 8, 7, 9, 0, 1, 2)

SortedSet([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering()))

## Building a custom Julia Stack implementation

In [67]:
struct Stack{T} 
  data::Vector{T} 
  size::Int 
 
  Stack{T}(data::Vector{T}, size::Int) where {T} = begin 
    length(data) > size &&  
      throw(StackOverflowException("The length of the data exceeds the size of the stack")) 
    size < 0 &&  
      throw(StackUnderflowException("The size of the stack can not be negative")) 
 
    new(data, size) 
  end 
end 

In [60]:
struct StackUnderflowException <: Exception 
  msg 
end 
 
struct StackOverflowException <: Exception 
  msg 
end 

In [61]:
Stack(data::Vector{T}, size::Int) where {T} = Stack{T}(data, size) 
Stack(data::Vector{T}) where {T} = Stack{T}(data, length(data)) 
 
Stack(itr, size) where {T} = Stack{eltype(itr)}([itr...], size) 
Stack(itr) where {T} = Stack{eltype(itr)}([itr...], length(itr)) 

Stack

In [62]:
Stack([1:10...])

Stack{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10)

In [63]:
s = Stack([1:10...], 100)

Stack{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 100)

In [64]:
Stack('a':'d')

Stack{Char}(['a', 'b', 'c', 'd'], 4)

In [65]:
Stack('a':'d', 24)

Stack{Char}(['a', 'b', 'c', 'd'], 24)

In [68]:
Stack(1:10, 5)

StackOverflowException: StackOverflowException("The length of the data exceeds the size of the stack")

### Working with stacks

In [70]:
function Base.push!(s::Stack{T}, elems::Vararg{T}) where {T} 
  length(s.data) + length(elems) > s.size &&  
    throw(StackOverflowException("Pushing $elems exceeds the size of the stack")) 
 
  Base.push!(s.data, elems...) 
end

In [71]:
s = Stack(1:10, 15)

Stack{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 15)

In [72]:
push!(s, 11, 12, 13)

13-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13

In [73]:
push!(s, 14, 15, 16)

StackOverflowException: StackOverflowException("Pushing (14, 15, 16) exceeds the size of the stack")

In [74]:
s

Stack{Int64}([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], 15)

In [75]:
push!(s, 14, 15)

15-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [76]:
function Base.pop!(s::Stack{T}) where {T} 
  length(s.data) > 0 ||  
    throw(StackUnderflowException("Stack can not be empty")) 
 
    pop!(s.data) 
end

In [77]:
s = Stack(1:3, 15)

Stack{Int64}([1, 2, 3], 15)

In [78]:
pop!(s)

3

In [79]:
pop!(s)

2

In [80]:
pop!(s)

1

In [81]:
pop!(s)

StackUnderflowException: StackUnderflowException("Stack can not be empty")

### Writing utility methods

In [82]:
function peek(s::Stack{T}) where {T} 
  length(s.data) > 0 ||  
    throw(StackUnderflowException("Stack can not be empty")) 
 
  s.data[end] 
end

peek (generic function with 1 method)

In [83]:
function Base.isempty(s::Stack{T}) where {T} 
  isempty(s.data) 
end 
 
function Base.length(s::Stack{T}) where {T} 
  length(s.data) 
end 
 
function Base.size(s::Stack{T}) where {T} 
  s.size 
end 
 
function isfull(s::Stack{T}) where {T} 
  length(s) == size(s) 
end 
 
function Base.empty!(s::Stack{T}) where{T} 
  empty!(s.data) 
  s 
end

In [84]:
s = Stack(1:3, 5)

Stack{Int64}([1, 2, 3], 5)

In [85]:
peek(s)

3

In [86]:
isempty(s)

false

In [87]:
length(s)

3

In [88]:
size(s)

5

In [89]:
isfull(s)

false

In [90]:
empty!(s)

Stack{Int64}(Int64[], 5)

In [91]:
peek(s)

StackUnderflowException: StackUnderflowException("Stack can not be empty")

In [92]:
isempty(s)

true

In [93]:
length(s)

0

In [94]:
size(s)

5

In [95]:
isfull(s)

false

In [96]:
empty!(s)

Stack{Int64}(Int64[], 5)

In [97]:
s = Stack(1:5)

Stack{Int64}([1, 2, 3, 4, 5], 5)

In [98]:
isempty(s)

false

In [99]:
length(s)

5

In [100]:
size(s)

5

In [101]:
isfull(s)

true

In [102]:
peek(s)

5

### Implementing Stack iteration

In [103]:
function Base.iterate(s::Stack{T}, state::Union{Stack,Nothing} = s) where {T} 
  (state === nothing || isempty(s)) && return nothing 
  pop!(s), s 
end

In [104]:
function Array(s::Stack{T}) where {T} 
  s.data |> reverse 
end

Array

In [108]:
s = Stack(1:3)

Stack{Int64}([1, 2, 3], 3)

In [109]:
for e in s 
    println(e) 
end

3
2
1


In [110]:
isempty(s)

true

In [111]:
s = Stack(1:3)

Stack{Int64}([1, 2, 3], 3)

In [112]:
for e in Array(s) 
    println(e) 
end

3
2
1


In [113]:
isempty(s)

false

In [114]:
function Base.eltype(s::Stack{T}) where {T} 
  eltype(s.data) 
end

### A Julia Queue implementation

In [1]:
include("LinkedLists.jl") 

Main.LinkedLists

In [2]:
using .LinkedLists

In [3]:
struct Queue{T} 
  list::LinkedList{T}
end

Queue(t::Type{T}) where {T} = Queue{T}(LinkedList{T}()) 
Queue{T}() where {T} = Queue{T}(LinkedList{T}()) 
Queue() = Queue{Any}(LinkedList{Any}())

Queue

In [4]:
q = Queue()

Queue{Any}(LinkedList::Any)

In [5]:
Queue{Char}()

Queue{Char}(LinkedList::Char)

In [6]:
Queue(Float16)

Queue{Float16}(LinkedList::Float16)

In [7]:
function enqueue!(q::Queue{T}, elem::T) where {T} 
  pushfirst!(q.list, Node(elem)) 
  q 
end 
 
function dequeue!(q::Queue{T}) where {T} 
  isempty(q) && throw(ArgumentError("Queue must not be empty")) 
  pop!(q.list).data 
end

dequeue! (generic function with 1 method)

In [8]:
function peek(q::Queue{T}) where {T} 
  isempty(q) && throw(ArgumentError("Queue must not be empty")) 
  (q.list[end]).data 
end 
 
function Base.length(q::Queue{T}) where {T} 
  length(q.list) 
end 
 
function Base.isempty(q::Queue{T}) where {T} 
  length(q) == 0 
end 
 
function Base.empty!(q::Queue{T}) where {T} 
  empty!(q.list) 
 
  q 
end 

In [9]:
q = Queue{Char}()

Queue{Char}(LinkedList::Char)

In [10]:
enqueue!(q, 'A')

Queue{Char}(LinkedList::Char [A]→)

In [11]:
enqueue!(q, 'B')

Queue{Char}(LinkedList::Char [B]→[A]→)

In [12]:
enqueue!(q, 'C')

Queue{Char}(LinkedList::Char [C]→[B]→[A]→)

In [13]:
isempty(q)

false

In [14]:
length(q)

3

In [15]:
dequeue!(q)

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [16]:
q

Queue{Char}(LinkedList::Char [C]→[B]→)

In [17]:
peek(q)

'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)

In [18]:
q

Queue{Char}(LinkedList::Char [C]→[B]→)

In [19]:
empty!(q)

Queue{Char}(LinkedList::Char)

In [20]:
isempty(q)

true

### Queue iteration

In [21]:
function Base.eltype(q::Queue{T}) where {T} 
  eltype(q.list) 
end 
 
function Base.iterate(q::Queue{T}, state::Union{Queue,Nothing} = q) where {T} 
  (state == nothing || isempty(q)) && return nothing 
  dequeue!(q), q 
end

In [22]:
q = Queue{Int}()

Queue{Int64}(LinkedList::Int64)

In [23]:
enqueue!(q, 1)

Queue{Int64}(LinkedList::Int64 [1]→)

In [24]:
enqueue!(q, 2)

Queue{Int64}(LinkedList::Int64 [2]→[1]→)

In [25]:
enqueue!(q, 3)

Queue{Int64}(LinkedList::Int64 [3]→[2]→[1]→)

In [26]:
for e in q 
   println(e) 
end

1
2
3


In [27]:
q

Queue{Int64}(LinkedList::Int64)